services:
  - type: static
    name: url-shortener-frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://url-shortener-fpql.onrender.com
      - key: NPM_CONFIG_PRODUCTION
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html