services:
  - type: static
    name: url-shortener-frontend
    buildCommand: cd frontend && npm install && npx vite build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://url-shortener-fpql.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html